/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.vista;

import java.awt.Dimension;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritoriopanel = new javax.swing.JDesktopPane();
        btnAdministrador = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnCocina = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritoriopanel.setBackground(new java.awt.Color(118, 155, 193));
        escritoriopanel.setForeground(java.awt.SystemColor.activeCaption);

        btnAdministrador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAdministrador.setForeground(new java.awt.Color(204, 204, 255));
        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/adm.png"))); // NOI18N
        btnAdministrador.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador"));
        btnAdministrador.setContentAreaFilled(false);
        btnAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        escritoriopanel.add(btnAdministrador);
        btnAdministrador.setBounds(170, 110, 169, 155);

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/menu.png"))); // NOI18N
        btnPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        btnPedido.setContentAreaFilled(false);
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        escritoriopanel.add(btnPedido);
        btnPedido.setBounds(460, 110, 169, 160);

        btnCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/cocinero.png"))); // NOI18N
        btnCocina.setBorder(javax.swing.BorderFactory.createTitledBorder("Cocina"));
        btnCocina.setContentAreaFilled(false);
        btnCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinaActionPerformed(evt);
            }
        });
        escritoriopanel.add(btnCocina);
        btnCocina.setBounds(780, 110, 169, 160);

        jButton6.setText("COnfigu");
        escritoriopanel.add(jButton6);
        jButton6.setBounds(480, 370, 160, 150);

        jButton5.setText("COnfigu");
        escritoriopanel.add(jButton5);
        jButton5.setBounds(790, 360, 160, 150);

        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dinero.png"))); // NOI18N
        btnPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));
        btnPago.setContentAreaFilled(false);
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        escritoriopanel.add(btnPago);
        btnPago.setBounds(170, 370, 169, 153);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Cerrar");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritoriopanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(escritoriopanel, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        int n = JOptionPane.showConfirmDialog(null, "¿Quiere cerrar el Modulo?",
                "Mensaje del sistema", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            //   JOptionPane.showMessageDialog(null, "...........");
            dispose();
            Login lg = new Login();
            lg.setVisible(true);
            //System.exit(0);
        }
       // System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        RegistroPlato pl = new RegistroPlato();
        escritoriopanel.add(pl);
   
        pl.setVisible(true);
       // pl.setLocation(WIDTH, WIDTH);
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        PedidoMesa me = new PedidoMesa();
        escritoriopanel.add(me);
        me.setVisible(true);
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinaActionPerformed
         CocinaValido c1 = new CocinaValido();
        escritoriopanel.add(c1); 
        c1.setVisible(true);


    }//GEN-LAST:event_btnCocinaActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed

    }//GEN-LAST:event_btnPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnCocina;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPedido;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritoriopanel;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
