/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurante.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class mesas extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public mesas() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnMesa1 = new javax.swing.JButton();
        btnMesa3 = new javax.swing.JButton();
        btnMesa2 = new javax.swing.JButton();
        btnMesa4 = new javax.swing.JButton();
        btnMesa5 = new javax.swing.JButton();
        btnMesa6 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        principalsalir = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMesa1.setForeground(new java.awt.Color(204, 204, 255));
        btnMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 1"));
        btnMesa1.setContentAreaFilled(false);
        btnMesa1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 150, 150));

        btnMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 3"));
        btnMesa3.setContentAreaFilled(false);
        btnMesa3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa3ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 160, 150));

        btnMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa2.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 2"));
        btnMesa2.setContentAreaFilled(false);
        btnMesa2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 150, 150));

        btnMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa4.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 4"));
        btnMesa4.setContentAreaFilled(false);
        btnMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa4ActionPerformed(evt);
            }
        });
        jPanel2.add(btnMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 150, 140));

        btnMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa5.setText("COnfigu");
        btnMesa5.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 5"));
        btnMesa5.setContentAreaFilled(false);
        jPanel2.add(btnMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 140, 130));

        btnMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dining-room.png"))); // NOI18N
        btnMesa6.setText("COnfigu");
        btnMesa6.setBorder(javax.swing.BorderFactory.createTitledBorder("Mesa 6"));
        btnMesa6.setContentAreaFilled(false);
        jPanel2.add(btnMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 150, 130));

        fondo.setBackground(new java.awt.Color(204, 204, 255));
        fondo.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 600));

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        principalsalir.setBackground(new java.awt.Color(51, 204, 255));
        principalsalir.setForeground(new java.awt.Color(255, 0, 0));
        principalsalir.setText("Salir");
        principalsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        principalsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalsalirMouseClicked(evt);
            }
        });
        principalsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalsalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(principalsalir);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa2ActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnMesa2ActionPerformed

    private void btnMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa1ActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnMesa1ActionPerformed

    private void btnMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa3ActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnMesa3ActionPerformed

    private void btnMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa4ActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnMesa4ActionPerformed

    private void principalsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalsalirActionPerformed
        dispose();
    }//GEN-LAST:event_principalsalirActionPerformed

    private void principalsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalsalirMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Quiere cerrar el Modulo?",
                "Mensaje del sistema", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            //   JOptionPane.showMessageDialog(null, "...........");
            Principal pr = new Principal();
            pr.setVisible(true);
            // System.exit(0);
        }
        //dispose();
    }//GEN-LAST:event_principalsalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMesa1;
    private javax.swing.JButton btnMesa2;
    private javax.swing.JButton btnMesa3;
    private javax.swing.JButton btnMesa4;
    private javax.swing.JButton btnMesa5;
    private javax.swing.JButton btnMesa6;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu principalsalir;
    // End of variables declaration//GEN-END:variables
}
