
package restaurante.vista;

import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {


    public Principal() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnAdministrador = new javax.swing.JButton();
        btnCocina = new javax.swing.JButton();
        btnPedido = new javax.swing.JButton();
        btnPago = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        principalsalir = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministrador.setForeground(new java.awt.Color(204, 204, 255));
        btnAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/adm.png"))); // NOI18N
        btnAdministrador.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrador"));
        btnAdministrador.setContentAreaFilled(false);
        btnAdministrador.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministradorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 150, 150));

        btnCocina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/cocinero.png"))); // NOI18N
        btnCocina.setBorder(javax.swing.BorderFactory.createTitledBorder("Cocina"));
        btnCocina.setContentAreaFilled(false);
        btnCocina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCocinaActionPerformed(evt);
            }
        });
        jPanel2.add(btnCocina, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 160, 150));

        btnPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/menu.png"))); // NOI18N
        btnPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        btnPedido.setContentAreaFilled(false);
        btnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 150, 150));

        btnPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurante/imagenes/dinero.png"))); // NOI18N
        btnPago.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagos"));
        btnPago.setContentAreaFilled(false);
        btnPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 150, 140));

        jButton5.setText("COnfigu");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 120, 120));

        jButton6.setText("COnfigu");
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 120, 120));

        fondo.setBackground(new java.awt.Color(204, 204, 255));
        fondo.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 660));

        jMenuBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        principalsalir.setBackground(new java.awt.Color(51, 204, 255));
        principalsalir.setForeground(new java.awt.Color(255, 0, 0));
        principalsalir.setText("Salir");
        principalsalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        principalsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                principalsalirMouseClicked(evt);
            }
        });
        principalsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                principalsalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(principalsalir);

        jMenu2.setText("Ayuda");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void principalsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_principalsalirActionPerformed
        dispose();
    }//GEN-LAST:event_principalsalirActionPerformed

    private void principalsalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_principalsalirMouseClicked
        int n = JOptionPane.showConfirmDialog(null, "¿Quiere cerrar el Modulo?",
                "Mensaje del sistema", JOptionPane.YES_NO_OPTION);
        if (n == JOptionPane.YES_OPTION) {
            //   JOptionPane.showMessageDialog(null, "...........");
            login lg = new login();
            lg.setVisible(true);
            //System.exit(0);
        }
        //dispose();
    }//GEN-LAST:event_principalsalirMouseClicked

    private void btnPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoActionPerformed
        mesas me = new mesas();
        me.setVisible(true);  
    }//GEN-LAST:event_btnPedidoActionPerformed

    private void btnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministradorActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnAdministradorActionPerformed

    private void btnCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCocinaActionPerformed
        cocina co = new cocina();
        co.setVisible(true);
    }//GEN-LAST:event_btnCocinaActionPerformed

    private void btnPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoActionPerformed
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_btnPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrador;
    private javax.swing.JButton btnCocina;
    private javax.swing.JButton btnPago;
    private javax.swing.JButton btnPedido;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu principalsalir;
    // End of variables declaration//GEN-END:variables
}
